// This JLex file was machine-generated by the BNF converter
package grammar;
import java_cup.runtime.*;


public class Yylex implements java_cup.runtime.Scanner {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() { return new String(yy_buffer,yy_buffer_index,10).trim(); }
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	public Yylex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	public Yylex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private Yylex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int STRING = 5;
	private final int ESCAPED = 6;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int CHAREND = 4;
	private final int CHARESC = 3;
	private final int CHAR = 2;
	private final int yy_state_dtrans[] = {
		0,
		46,
		50,
		50,
		50,
		50,
		50
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private java.lang.String yytext () {
		return (new java.lang.String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private java.lang.String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		java.lang.System.out.print(yy_error_string[code]);
		java.lang.System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NO_ANCHOR,
		/* 39 */ YY_NOT_ACCEPT,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NOT_ACCEPT,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NOT_ACCEPT,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NOT_ACCEPT,
		/* 49 */ YY_NO_ANCHOR,
		/* 50 */ YY_NOT_ACCEPT,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NO_ANCHOR,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NO_ANCHOR,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NO_ANCHOR,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NO_ANCHOR,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NO_ANCHOR,
		/* 64 */ YY_NO_ANCHOR,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR,
		/* 76 */ YY_NO_ANCHOR,
		/* 77 */ YY_NO_ANCHOR,
		/* 78 */ YY_NO_ANCHOR,
		/* 79 */ YY_NO_ANCHOR,
		/* 80 */ YY_NO_ANCHOR,
		/* 81 */ YY_NO_ANCHOR,
		/* 82 */ YY_NO_ANCHOR,
		/* 83 */ YY_NO_ANCHOR,
		/* 84 */ YY_NO_ANCHOR,
		/* 85 */ YY_NO_ANCHOR,
		/* 86 */ YY_NO_ANCHOR,
		/* 87 */ YY_NO_ANCHOR,
		/* 88 */ YY_NO_ANCHOR,
		/* 89 */ YY_NO_ANCHOR,
		/* 90 */ YY_NO_ANCHOR,
		/* 91 */ YY_NO_ANCHOR,
		/* 92 */ YY_NO_ANCHOR,
		/* 93 */ YY_NO_ANCHOR,
		/* 94 */ YY_NO_ANCHOR,
		/* 95 */ YY_NO_ANCHOR,
		/* 96 */ YY_NO_ANCHOR,
		/* 97 */ YY_NO_ANCHOR,
		/* 98 */ YY_NO_ANCHOR,
		/* 99 */ YY_NO_ANCHOR,
		/* 100 */ YY_NO_ANCHOR,
		/* 101 */ YY_NO_ANCHOR,
		/* 102 */ YY_NO_ANCHOR,
		/* 103 */ YY_NO_ANCHOR,
		/* 104 */ YY_NO_ANCHOR,
		/* 105 */ YY_NO_ANCHOR,
		/* 106 */ YY_NO_ANCHOR,
		/* 107 */ YY_NO_ANCHOR,
		/* 108 */ YY_NO_ANCHOR,
		/* 109 */ YY_NO_ANCHOR,
		/* 110 */ YY_NO_ANCHOR,
		/* 111 */ YY_NO_ANCHOR,
		/* 112 */ YY_NO_ANCHOR,
		/* 113 */ YY_NO_ANCHOR,
		/* 114 */ YY_NO_ANCHOR,
		/* 115 */ YY_NO_ANCHOR,
		/* 116 */ YY_NO_ANCHOR,
		/* 117 */ YY_NO_ANCHOR,
		/* 118 */ YY_NO_ANCHOR,
		/* 119 */ YY_NO_ANCHOR,
		/* 120 */ YY_NO_ANCHOR,
		/* 121 */ YY_NO_ANCHOR,
		/* 122 */ YY_NO_ANCHOR,
		/* 123 */ YY_NO_ANCHOR,
		/* 124 */ YY_NO_ANCHOR,
		/* 125 */ YY_NO_ANCHOR,
		/* 126 */ YY_NO_ANCHOR,
		/* 127 */ YY_NO_ANCHOR,
		/* 128 */ YY_NO_ANCHOR,
		/* 129 */ YY_NO_ANCHOR,
		/* 130 */ YY_NO_ANCHOR,
		/* 131 */ YY_NO_ANCHOR,
		/* 132 */ YY_NO_ANCHOR,
		/* 133 */ YY_NO_ANCHOR,
		/* 134 */ YY_NO_ANCHOR,
		/* 135 */ YY_NO_ANCHOR,
		/* 136 */ YY_NO_ANCHOR,
		/* 137 */ YY_NO_ANCHOR,
		/* 138 */ YY_NO_ANCHOR,
		/* 139 */ YY_NO_ANCHOR,
		/* 140 */ YY_NO_ANCHOR,
		/* 141 */ YY_NO_ANCHOR,
		/* 142 */ YY_NO_ANCHOR,
		/* 143 */ YY_NO_ANCHOR,
		/* 144 */ YY_NO_ANCHOR,
		/* 145 */ YY_NO_ANCHOR,
		/* 146 */ YY_NO_ANCHOR,
		/* 147 */ YY_NO_ANCHOR,
		/* 148 */ YY_NO_ANCHOR,
		/* 149 */ YY_NO_ANCHOR,
		/* 150 */ YY_NO_ANCHOR,
		/* 151 */ YY_NO_ANCHOR,
		/* 152 */ YY_NO_ANCHOR,
		/* 153 */ YY_NO_ANCHOR,
		/* 154 */ YY_NO_ANCHOR,
		/* 155 */ YY_NO_ANCHOR,
		/* 156 */ YY_NO_ANCHOR,
		/* 157 */ YY_NO_ANCHOR,
		/* 158 */ YY_NO_ANCHOR,
		/* 159 */ YY_NO_ANCHOR,
		/* 160 */ YY_NO_ANCHOR,
		/* 161 */ YY_NO_ANCHOR,
		/* 162 */ YY_NO_ANCHOR,
		/* 163 */ YY_NO_ANCHOR,
		/* 164 */ YY_NO_ANCHOR,
		/* 165 */ YY_NO_ANCHOR,
		/* 166 */ YY_NO_ANCHOR,
		/* 167 */ YY_NO_ANCHOR,
		/* 168 */ YY_NO_ANCHOR,
		/* 169 */ YY_NO_ANCHOR,
		/* 170 */ YY_NO_ANCHOR,
		/* 171 */ YY_NO_ANCHOR,
		/* 172 */ YY_NO_ANCHOR,
		/* 173 */ YY_NO_ANCHOR,
		/* 174 */ YY_NO_ANCHOR,
		/* 175 */ YY_NO_ANCHOR,
		/* 176 */ YY_NO_ANCHOR,
		/* 177 */ YY_NO_ANCHOR,
		/* 178 */ YY_NO_ANCHOR,
		/* 179 */ YY_NO_ANCHOR,
		/* 180 */ YY_NO_ANCHOR,
		/* 181 */ YY_NO_ANCHOR,
		/* 182 */ YY_NO_ANCHOR,
		/* 183 */ YY_NO_ANCHOR,
		/* 184 */ YY_NO_ANCHOR,
		/* 185 */ YY_NO_ANCHOR,
		/* 186 */ YY_NO_ANCHOR,
		/* 187 */ YY_NO_ANCHOR,
		/* 188 */ YY_NO_ANCHOR,
		/* 189 */ YY_NO_ANCHOR,
		/* 190 */ YY_NO_ANCHOR,
		/* 191 */ YY_NO_ANCHOR,
		/* 192 */ YY_NO_ANCHOR,
		/* 193 */ YY_NO_ANCHOR,
		/* 194 */ YY_NO_ANCHOR,
		/* 195 */ YY_NO_ANCHOR,
		/* 196 */ YY_NO_ANCHOR,
		/* 197 */ YY_NO_ANCHOR,
		/* 198 */ YY_NO_ANCHOR,
		/* 199 */ YY_NO_ANCHOR,
		/* 200 */ YY_NO_ANCHOR,
		/* 201 */ YY_NO_ANCHOR,
		/* 202 */ YY_NO_ANCHOR,
		/* 203 */ YY_NO_ANCHOR,
		/* 204 */ YY_NO_ANCHOR,
		/* 205 */ YY_NO_ANCHOR,
		/* 206 */ YY_NO_ANCHOR,
		/* 207 */ YY_NO_ANCHOR,
		/* 208 */ YY_NO_ANCHOR,
		/* 209 */ YY_NO_ANCHOR,
		/* 210 */ YY_NO_ANCHOR,
		/* 211 */ YY_NO_ANCHOR,
		/* 212 */ YY_NO_ANCHOR,
		/* 213 */ YY_NO_ANCHOR,
		/* 214 */ YY_NO_ANCHOR,
		/* 215 */ YY_NO_ANCHOR,
		/* 216 */ YY_NO_ANCHOR,
		/* 217 */ YY_NO_ANCHOR,
		/* 218 */ YY_NO_ANCHOR,
		/* 219 */ YY_NO_ANCHOR,
		/* 220 */ YY_NO_ANCHOR,
		/* 221 */ YY_NO_ANCHOR,
		/* 222 */ YY_NO_ANCHOR,
		/* 223 */ YY_NO_ANCHOR,
		/* 224 */ YY_NO_ANCHOR,
		/* 225 */ YY_NO_ANCHOR,
		/* 226 */ YY_NO_ANCHOR,
		/* 227 */ YY_NO_ANCHOR,
		/* 228 */ YY_NO_ANCHOR,
		/* 229 */ YY_NO_ANCHOR,
		/* 230 */ YY_NO_ANCHOR,
		/* 231 */ YY_NO_ANCHOR,
		/* 232 */ YY_NO_ANCHOR,
		/* 233 */ YY_NO_ANCHOR,
		/* 234 */ YY_NO_ANCHOR,
		/* 235 */ YY_NO_ANCHOR,
		/* 236 */ YY_NO_ANCHOR,
		/* 237 */ YY_NO_ANCHOR,
		/* 238 */ YY_NO_ANCHOR,
		/* 239 */ YY_NO_ANCHOR,
		/* 240 */ YY_NO_ANCHOR,
		/* 241 */ YY_NO_ANCHOR,
		/* 242 */ YY_NO_ANCHOR,
		/* 243 */ YY_NO_ANCHOR,
		/* 244 */ YY_NO_ANCHOR,
		/* 245 */ YY_NO_ANCHOR,
		/* 246 */ YY_NO_ANCHOR,
		/* 247 */ YY_NO_ANCHOR,
		/* 248 */ YY_NO_ANCHOR,
		/* 249 */ YY_NO_ANCHOR,
		/* 250 */ YY_NO_ANCHOR,
		/* 251 */ YY_NO_ANCHOR,
		/* 252 */ YY_NO_ANCHOR,
		/* 253 */ YY_NO_ANCHOR,
		/* 254 */ YY_NO_ANCHOR,
		/* 255 */ YY_NO_ANCHOR,
		/* 256 */ YY_NO_ANCHOR,
		/* 257 */ YY_NO_ANCHOR,
		/* 258 */ YY_NO_ANCHOR,
		/* 259 */ YY_NO_ANCHOR,
		/* 260 */ YY_NO_ANCHOR,
		/* 261 */ YY_NO_ANCHOR,
		/* 262 */ YY_NO_ANCHOR,
		/* 263 */ YY_NO_ANCHOR,
		/* 264 */ YY_NO_ANCHOR,
		/* 265 */ YY_NO_ANCHOR,
		/* 266 */ YY_NO_ANCHOR,
		/* 267 */ YY_NO_ANCHOR,
		/* 268 */ YY_NO_ANCHOR,
		/* 269 */ YY_NO_ANCHOR,
		/* 270 */ YY_NO_ANCHOR,
		/* 271 */ YY_NO_ANCHOR,
		/* 272 */ YY_NO_ANCHOR,
		/* 273 */ YY_NO_ANCHOR,
		/* 274 */ YY_NO_ANCHOR,
		/* 275 */ YY_NO_ANCHOR,
		/* 276 */ YY_NO_ANCHOR,
		/* 277 */ YY_NO_ANCHOR,
		/* 278 */ YY_NO_ANCHOR,
		/* 279 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"46:9,49,44,46,49,43,46:18,49,46:9,45,46,9,5,8,7,48:10,3,4,46:2,6,46:2,36,10" +
",32,47:2,42,29,47,13,47:2,35,47:3,39,47,41,28,18,30,47,38,47:3,46:4,47,46,1" +
"1,47,22,12,23,47,25,33,15,47,34,17,27,14,21,24,47,19,20,16,26,37,47,31,40,4" +
"7,1,46,2,46:66,47:23,46,47:31,46,47:8,46:65280,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,280,
"0,1:5,2,1,3,1,4,1,5,1:3,6,7,6:3,8,6:13,1:4,9,10,11,12,6,13,14,15,16,17,18,1" +
"9,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,4" +
"4,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,6" +
"9,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,9" +
"4,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,11" +
"4,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,1" +
"33,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151," +
"152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170" +
",171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,18" +
"9,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,6,206,207" +
",208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,22" +
"6,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,2" +
"45,246,247")[0];

	private int yy_nxt[][] = unpackFromString(248,50,
"1,2,3,4,5,39,-1,6,42,7,8,194,237,251,258,261,263,264,279,265,266,237,267,26" +
"8,269,237,270,271,237:15,9:2,-1:2,237,10,9,-1:57,44,-1:37,12,-1:14,237,40,2" +
"37:31,-1:4,237,43,-1:11,237:33,-1:4,237,10,-1:46,15,-1:14,237:33,-1:4,237,4" +
"3,-1:11,237:26,77,237:6,-1:4,237,43,-1:11,237:18,114,237:14,-1:4,237,43,-1:" +
"7,11,-1:53,237:2,16,237:30,-1:4,237,43,-1:8,37,-1:37,48,-1:12,13,-1:42,44:4" +
"3,14,44:5,-1:10,237:12,199,237:20,-1:4,237,43,-1,1,35:42,-1,36,41,35:4,-1:1" +
"0,237:6,60,237:26,-1:4,237,43,-1:8,38,-1:52,237:5,61,237:27,-1:4,237,43,-1," +
"1,-1:59,237:29,198,237:3,-1:4,237,43,-1:11,237,200,237:31,-1:4,237,43,-1:11" +
",237:11,63,237:3,64,237:17,-1:4,237,43,-1:11,237:17,197,237:15,-1:4,237,43," +
"-1:11,237:11,66,237:21,-1:4,237,43,-1:11,237:14,67,237:18,-1:4,237,43,-1:11" +
",237:9,201,237:23,-1:4,237,43,-1:11,237:13,68,237:19,-1:4,237,43,-1:11,237:" +
"4,69,237:28,-1:4,237,43,-1:11,237:11,238,237:21,-1:4,237,43,-1:11,237:6,71," +
"237:26,-1:4,237,43,-1:11,237:6,17,237:26,-1:4,237,43,-1:11,237:14,18,237:18" +
",-1:4,237,43,-1:11,237:25,204,237:7,-1:4,237,43,-1:11,237,73,237:31,-1:4,23" +
"7,43,-1:11,237:10,253,237:22,-1:4,237,43,-1:11,237:7,203,237:25,-1:4,237,43" +
",-1:11,237:31,75,237,-1:4,237,43,-1:11,237:11,205,237:21,-1:4,237,43,-1:11," +
"237:14,273,237:18,-1:4,237,43,-1:11,237:5,242,237:27,-1:4,237,43,-1:11,237:" +
"13,76,237:19,-1:4,237,43,-1:11,237:6,208,237:26,-1:4,237,43,-1:11,237:7,241" +
",237:25,-1:4,237,43,-1:11,237,83,237:31,-1:4,237,43,-1:11,237:12,272,237:20" +
",-1:4,237,43,-1:11,237:16,85,237:16,-1:4,237,43,-1:11,237:2,86,237:30,-1:4," +
"237,43,-1:11,237:27,87,237:5,-1:4,237,43,-1:11,237:5,244,237:27,-1:4,237,43" +
",-1:11,237:6,89,237:26,-1:4,237,43,-1:11,237:12,91,237:20,-1:4,237,43,-1:11" +
",237:4,92,237:28,-1:4,237,43,-1:11,237:7,19,237:25,-1:4,237,43,-1:11,237:6," +
"277,237:26,-1:4,237,43,-1:11,237:16,95,237:16,-1:4,237,43,-1:11,237:13,96,2" +
"37:19,-1:4,237,43,-1:11,237:11,97,237:21,-1:4,237,43,-1:11,237:9,245,237:23" +
",-1:4,237,43,-1:11,237:20,214,237:12,-1:4,237,43,-1:11,237:5,213,237:27,-1:" +
"4,237,43,-1:11,237:24,99,237:8,-1:4,237,43,-1:11,237:6,100,237:26,-1:4,237," +
"43,-1:11,237:4,101,237:28,-1:4,237,43,-1:11,237:12,104,237:20,-1:4,237,43,-" +
"1:11,237:7,20,237:25,-1:4,237,43,-1:11,237:4,21,237:28,-1:4,237,43,-1:11,23" +
"7:7,22,237:25,-1:4,237,43,-1:11,237:5,215,237:27,-1:4,237,43,-1:11,237:23,1" +
"08,237:9,-1:4,237,43,-1:11,237:15,23,237:17,-1:4,237,43,-1:11,237:4,109,237" +
":28,-1:4,237,43,-1:11,237:14,110,237:18,-1:4,237,43,-1:11,237:13,112,237:19" +
",-1:4,237,43,-1:11,237:11,113,237:21,-1:4,237,43,-1:11,237:2,116,237:30,-1:" +
"4,237,43,-1:11,237:22,117,237:10,-1:4,237,43,-1:11,237:5,119,237:27,-1:4,23" +
"7,43,-1:11,237:18,274,237:14,-1:4,237,43,-1:11,237:16,217,237:16,-1:4,237,4" +
"3,-1:11,237,246,237:31,-1:4,237,43,-1:11,237:9,120,237:23,-1:4,237,43,-1:11" +
",237:4,24,237:28,-1:4,237,43,-1:11,237:6,121,237:26,-1:4,237,43,-1:11,237:1" +
"0,25,237:22,-1:4,237,43,-1:11,237:13,122,237:19,-1:4,237,43,-1:11,237:23,12" +
"3,237:9,-1:4,237,43,-1:11,237:15,124,237:17,-1:4,237,43,-1:11,237:12,125,23" +
"7:20,-1:4,237,43,-1:11,237:18,127,237:14,-1:4,237,43,-1:11,237,219,237:31,-" +
"1:4,237,43,-1:11,237:9,128,237:23,-1:4,237,43,-1:11,237:13,129,237:19,-1:4," +
"237,43,-1:11,237:32,130,-1:4,237,43,-1:11,237:28,131,237:4,-1:4,237,43,-1:1" +
"1,237:11,133,237:21,-1:4,237,43,-1:11,237:6,134,237:26,-1:4,237,43,-1:11,23" +
"7:8,136,237:24,-1:4,237,43,-1:11,237:12,137,237:20,-1:4,237,43,-1:11,237:16" +
",222,237:16,-1:4,237,43,-1:11,237:5,223,237:27,-1:4,237,43,-1:11,237:2,139," +
"237:30,-1:4,237,43,-1:11,237:4,140,237:28,-1:4,237,43,-1:11,237,247,237:31," +
"-1:4,237,43,-1:11,237:6,141,237:26,-1:4,237,43,-1:11,237:9,142,237:23,-1:4," +
"237,43,-1:11,237:24,143,237:8,-1:4,237,43,-1:11,237:13,146,237:19,-1:4,237," +
"43,-1:11,237:3,224,237:29,-1:4,237,43,-1:11,237:18,147,237:14,-1:4,237,43,-" +
"1:11,237:5,248,237:27,-1:4,237,43,-1:11,237,256,237:31,-1:4,237,43,-1:11,23" +
"7:10,149,237:22,-1:4,237,43,-1:11,237:12,225,237:20,-1:4,237,43,-1:11,237:4" +
",226,237:28,-1:4,237,43,-1:11,237:19,150,237:13,-1:4,237,43,-1:11,237:6,152" +
",237:26,-1:4,237,43,-1:11,237:13,153,237:19,-1:4,237,43,-1:11,237:20,156,23" +
"7:12,-1:4,237,43,-1:11,237:16,158,237:16,-1:4,237,43,-1:11,237:27,227,237:5" +
",-1:4,237,43,-1:11,237,159,237:31,-1:4,237,43,-1:11,237:19,160,237:13,-1:4," +
"237,43,-1:11,237:15,161,237:17,-1:4,237,43,-1:11,237:10,229,237:22,-1:4,237" +
",43,-1:11,237:4,230,237:28,-1:4,237,43,-1:11,237:5,162,237:27,-1:4,237,43,-" +
"1:11,237:13,164,237:19,-1:4,237,43,-1:11,237:6,166,237:26,-1:4,237,43,-1:11" +
",237:16,167,237:16,-1:4,237,43,-1:11,237:28,168,237:4,-1:4,237,43,-1:11,237" +
":11,171,237:21,-1:4,237,43,-1:11,237:10,26,237:22,-1:4,237,43,-1:11,237:10," +
"231,237:22,-1:4,237,43,-1:11,237:9,232,237:23,-1:4,237,43,-1:11,237:13,172," +
"237:19,-1:4,237,43,-1:11,237:13,249,237:19,-1:4,237,43,-1:11,237:5,233,237:" +
"27,-1:4,237,43,-1:11,237:6,173,237:26,-1:4,237,43,-1:11,237:5,254,237:27,-1" +
":4,237,43,-1:11,237:4,174,237:28,-1:4,237,43,-1:11,237:19,176,237:13,-1:4,2" +
"37,43,-1:11,237:5,178,237:27,-1:4,237,43,-1:11,237:10,27,237:22,-1:4,237,43" +
",-1:11,237,235,237:31,-1:4,237,43,-1:11,237:16,275,237:16,-1:4,237,43,-1:11" +
",237:23,28,237:9,-1:4,237,43,-1:11,237:11,250,237:21,-1:4,237,43,-1:11,237:" +
"25,182,237:7,-1:4,237,43,-1:11,237:4,183,237:28,-1:4,237,43,-1:11,237:5,185" +
",237:27,-1:4,237,43,-1:11,237:13,236,237:19,-1:4,237,43,-1:11,237:15,29,237" +
":17,-1:4,237,43,-1:11,237:6,30,237:26,-1:4,237,43,-1:11,237:4,187,237:28,-1" +
":4,237,43,-1:11,237:10,31,237:22,-1:4,237,43,-1:11,237:15,32,237:17,-1:4,23" +
"7,43,-1:11,237:15,190,237:17,-1:4,237,43,-1:11,237:5,191,237:27,-1:4,237,43" +
",-1:11,237:6,192,237:26,-1:4,237,43,-1:11,237:4,193,237:28,-1:4,237,43,-1:1" +
"1,237:23,33,237:9,-1:4,237,43,-1:11,237:15,34,237:17,-1:4,237,43,-1:11,237:" +
"12,45,237:3,47,237:16,-1:4,237,43,-1:11,237:6,65,237:26,-1:4,237,43,-1:11,2" +
"37:5,62,237:27,-1:4,237,43,-1:11,237:17,240,237:15,-1:4,237,43,-1:11,237:9," +
"72,237:23,-1:4,237,43,-1:11,237:13,70,237:19,-1:4,237,43,-1:11,237:4,202,23" +
"7:28,-1:4,237,43,-1:11,237,74,237:31,-1:4,237,43,-1:11,237:10,78,237:22,-1:" +
"4,237,43,-1:11,237:5,82,237:27,-1:4,237,43,-1:11,237:13,79,237:19,-1:4,237," +
"43,-1:11,237:7,243,237:25,-1:4,237,43,-1:11,237,209,237:31,-1:4,237,43,-1:1" +
"1,237:2,90,237:30,-1:4,237,43,-1:11,237:5,88,237:27,-1:4,237,43,-1:11,237:6" +
",211,237:26,-1:4,237,43,-1:11,237:13,98,237:19,-1:4,237,43,-1:11,237:11,102" +
",237:21,-1:4,237,43,-1:11,237:5,105,237:27,-1:4,237,43,-1:11,237:6,107,237:" +
"26,-1:4,237,43,-1:11,237:4,106,237:28,-1:4,237,43,-1:11,237:4,118,237:28,-1" +
":4,237,43,-1:11,237:13,115,237:19,-1:4,237,43,-1:11,237:6,220,237:26,-1:4,2" +
"37,43,-1:11,237,221,237:31,-1:4,237,43,-1:11,237:9,135,237:23,-1:4,237,43,-" +
"1:11,237:13,132,237:19,-1:4,237,43,-1:11,237:6,138,237:26,-1:4,237,43,-1:11" +
",237:4,144,237:28,-1:4,237,43,-1:11,237:6,145,237:26,-1:4,237,43,-1:11,237:" +
"4,151,237:28,-1:4,237,43,-1:11,237:6,157,237:26,-1:4,237,43,-1:11,237:13,22" +
"8,237:19,-1:4,237,43,-1:11,237,165,237:31,-1:4,237,43,-1:11,237:10,163,237:" +
"22,-1:4,237,43,-1:11,237:5,169,237:27,-1:4,237,43,-1:11,237:6,170,237:26,-1" +
":4,237,43,-1:11,237:10,234,237:22,-1:4,237,43,-1:11,237:5,175,237:27,-1:4,2" +
"37,43,-1:11,237:6,177,237:26,-1:4,237,43,-1:11,237:5,180,237:27,-1:4,237,43" +
",-1:11,237:4,184,237:28,-1:4,237,43,-1:11,237:4,188,237:28,-1:4,237,43,-1:1" +
"1,237:17,206,237:15,-1:4,237,43,-1:11,237:10,80,237:22,-1:4,237,43,-1:11,23" +
"7:13,81,237:19,-1:4,237,43,-1:11,237:7,210,237:25,-1:4,237,43,-1:11,237,84," +
"237:31,-1:4,237,43,-1:11,237:5,93,237:27,-1:4,237,43,-1:11,237:6,212,237:26" +
",-1:4,237,43,-1:11,237:5,216,237:27,-1:4,237,43,-1:11,237:6,126,237:26,-1:4" +
",237,43,-1:11,237:6,148,237:26,-1:4,237,43,-1:11,237:4,154,237:28,-1:4,237," +
"43,-1:11,237:10,257,237:22,-1:4,237,43,-1:11,237:4,186,237:28,-1:4,237,43,-" +
"1:11,237:4,49,237:28,-1:4,237,43,-1:11,237:17,103,237:15,-1:4,237,43,-1:11," +
"237:13,207,237:19,-1:4,237,43,-1:11,237:7,179,237:25,-1:4,237,43,-1:11,237:" +
"5,94,237:27,-1:4,237,43,-1:11,237:4,155,237:28,-1:4,237,43,-1:11,237:10,181" +
",237:22,-1:4,237,43,-1:11,237:11,51,237:21,-1:4,237,43,-1:11,237:17,111,237" +
":15,-1:4,237,43,-1:11,237:10,262,237:22,-1:4,237,43,-1:11,237:4,196,237:28," +
"-1:4,237,43,-1:11,237:10,189,237:22,-1:4,237,43,-1:11,237:9,52,237:23,-1:4," +
"237,43,-1:11,237:11,53,237:21,-1:4,237,43,-1:11,237:11,195,237:21,-1:4,237," +
"43,-1:11,237:30,54,237:2,-1:4,237,43,-1:11,237:7,55,237:25,-1:4,237,43,-1:1" +
"1,237:21,56,237:11,-1:4,237,43,-1:11,237,57,237:31,-1:4,237,43,-1:11,237:10" +
",58,237:22,-1:4,237,43,-1:11,237:11,59,237:21,-1:4,237,43,-1:11,237:11,252," +
"237:21,-1:4,237,43,-1:11,237:6,255,237:26,-1:4,237,43,-1:11,237:6,218,237:2" +
"6,-1:4,237,43,-1:11,237:13,260,237:19,-1:4,237,43,-1:11,237:4,239,237:28,-1" +
":4,237,43,-1:11,237:11,259,237:21,-1:4,237,43,-1:11,237,276,237:31,-1:4,237" +
",43,-1:11,237:9,278,237:23,-1:4,237,43,-1");

	public java_cup.runtime.Symbol next_token ()
		throws java.io.IOException {
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return new Symbol(sym._SYMB_0); }
					case -3:
						break;
					case 3:
						{ return new Symbol(sym._SYMB_1); }
					case -4:
						break;
					case 4:
						{ return new Symbol(sym._SYMB_2); }
					case -5:
						break;
					case 5:
						{ return new Symbol(sym._SYMB_3); }
					case -6:
						break;
					case 6:
						{ return new Symbol(sym._SYMB_5); }
					case -7:
						break;
					case 7:
						{ return new Symbol(sym._SYMB_7); }
					case -8:
						break;
					case 8:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -9:
						break;
					case 9:
						{ /* ignore white space. */ }
					case -10:
						break;
					case 10:
						{ return new Symbol(sym.MyInteger, yytext().intern()); }
					case -11:
						break;
					case 11:
						{ return new Symbol(sym._SYMB_4); }
					case -12:
						break;
					case 12:
						{ yybegin(COMMENT); }
					case -13:
						break;
					case 13:
						{ return new Symbol(sym._SYMB_6); }
					case -14:
						break;
					case 14:
						{ /* BNFC single-line comment */ }
					case -15:
						break;
					case 15:
						{ yybegin(COMMENT); }
					case -16:
						break;
					case 16:
						{ return new Symbol(sym._SYMB_8); }
					case -17:
						break;
					case 17:
						{ return new Symbol(sym._SYMB_15); }
					case -18:
						break;
					case 18:
						{ return new Symbol(sym._SYMB_18); }
					case -19:
						break;
					case 19:
						{ return new Symbol(sym._SYMB_9); }
					case -20:
						break;
					case 20:
						{ return new Symbol(sym._SYMB_17); }
					case -21:
						break;
					case 21:
						{ return new Symbol(sym._SYMB_22); }
					case -22:
						break;
					case 22:
						{ return new Symbol(sym._SYMB_21); }
					case -23:
						break;
					case 23:
						{ return new Symbol(sym._SYMB_11); }
					case -24:
						break;
					case 24:
						{ return new Symbol(sym._SYMB_10); }
					case -25:
						break;
					case 25:
						{ return new Symbol(sym._SYMB_24); }
					case -26:
						break;
					case 26:
						{ return new Symbol(sym._SYMB_19); }
					case -27:
						break;
					case 27:
						{ return new Symbol(sym._SYMB_26); }
					case -28:
						break;
					case 28:
						{ return new Symbol(sym._SYMB_23); }
					case -29:
						break;
					case 29:
						{ return new Symbol(sym._SYMB_12); }
					case -30:
						break;
					case 30:
						{ return new Symbol(sym._SYMB_20); }
					case -31:
						break;
					case 31:
						{ return new Symbol(sym._SYMB_13); }
					case -32:
						break;
					case 32:
						{ return new Symbol(sym._SYMB_25); }
					case -33:
						break;
					case 33:
						{ return new Symbol(sym._SYMB_14); }
					case -34:
						break;
					case 34:
						{ return new Symbol(sym._SYMB_16); }
					case -35:
						break;
					case 35:
						{ }
					case -36:
						break;
					case 36:
						{ }
					case -37:
						break;
					case 37:
						{ yybegin(YYINITIAL); }
					case -38:
						break;
					case 38:
						{ yybegin(YYINITIAL); }
					case -39:
						break;
					case 40:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -40:
						break;
					case 41:
						{ }
					case -41:
						break;
					case 43:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -42:
						break;
					case 45:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -43:
						break;
					case 47:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -44:
						break;
					case 49:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -45:
						break;
					case 51:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -46:
						break;
					case 52:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -47:
						break;
					case 53:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -48:
						break;
					case 54:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -49:
						break;
					case 55:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -50:
						break;
					case 56:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -51:
						break;
					case 57:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -52:
						break;
					case 58:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -53:
						break;
					case 59:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -54:
						break;
					case 60:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -55:
						break;
					case 61:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -56:
						break;
					case 62:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -57:
						break;
					case 63:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -58:
						break;
					case 64:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -59:
						break;
					case 65:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -60:
						break;
					case 66:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -61:
						break;
					case 67:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -62:
						break;
					case 68:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -63:
						break;
					case 69:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -64:
						break;
					case 70:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -65:
						break;
					case 71:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -66:
						break;
					case 72:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -67:
						break;
					case 73:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -68:
						break;
					case 74:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -69:
						break;
					case 75:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -70:
						break;
					case 76:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -71:
						break;
					case 77:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -72:
						break;
					case 78:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -73:
						break;
					case 79:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -74:
						break;
					case 80:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -75:
						break;
					case 81:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -76:
						break;
					case 82:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -77:
						break;
					case 83:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -78:
						break;
					case 84:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -79:
						break;
					case 85:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -80:
						break;
					case 86:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -81:
						break;
					case 87:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -82:
						break;
					case 88:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -83:
						break;
					case 89:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -84:
						break;
					case 90:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -85:
						break;
					case 91:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -86:
						break;
					case 92:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -87:
						break;
					case 93:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -88:
						break;
					case 94:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -89:
						break;
					case 95:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -90:
						break;
					case 96:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -91:
						break;
					case 97:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -92:
						break;
					case 98:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -93:
						break;
					case 99:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -94:
						break;
					case 100:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -95:
						break;
					case 101:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -96:
						break;
					case 102:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -97:
						break;
					case 103:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -98:
						break;
					case 104:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -99:
						break;
					case 105:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -100:
						break;
					case 106:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -101:
						break;
					case 107:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -102:
						break;
					case 108:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -103:
						break;
					case 109:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -104:
						break;
					case 110:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -105:
						break;
					case 111:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -106:
						break;
					case 112:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -107:
						break;
					case 113:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -108:
						break;
					case 114:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -109:
						break;
					case 115:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -110:
						break;
					case 116:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -111:
						break;
					case 117:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -112:
						break;
					case 118:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -113:
						break;
					case 119:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -114:
						break;
					case 120:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -115:
						break;
					case 121:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -116:
						break;
					case 122:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -117:
						break;
					case 123:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -118:
						break;
					case 124:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -119:
						break;
					case 125:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -120:
						break;
					case 126:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -121:
						break;
					case 127:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -122:
						break;
					case 128:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -123:
						break;
					case 129:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -124:
						break;
					case 130:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -125:
						break;
					case 131:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -126:
						break;
					case 132:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -127:
						break;
					case 133:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -128:
						break;
					case 134:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -129:
						break;
					case 135:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -130:
						break;
					case 136:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -131:
						break;
					case 137:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -132:
						break;
					case 138:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -133:
						break;
					case 139:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -134:
						break;
					case 140:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -135:
						break;
					case 141:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -136:
						break;
					case 142:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -137:
						break;
					case 143:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -138:
						break;
					case 144:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -139:
						break;
					case 145:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -140:
						break;
					case 146:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -141:
						break;
					case 147:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -142:
						break;
					case 148:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -143:
						break;
					case 149:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -144:
						break;
					case 150:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -145:
						break;
					case 151:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -146:
						break;
					case 152:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -147:
						break;
					case 153:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -148:
						break;
					case 154:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -149:
						break;
					case 155:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -150:
						break;
					case 156:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -151:
						break;
					case 157:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -152:
						break;
					case 158:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -153:
						break;
					case 159:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -154:
						break;
					case 160:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -155:
						break;
					case 161:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -156:
						break;
					case 162:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -157:
						break;
					case 163:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -158:
						break;
					case 164:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -159:
						break;
					case 165:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -160:
						break;
					case 166:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -161:
						break;
					case 167:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -162:
						break;
					case 168:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -163:
						break;
					case 169:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -164:
						break;
					case 170:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -165:
						break;
					case 171:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -166:
						break;
					case 172:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -167:
						break;
					case 173:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -168:
						break;
					case 174:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -169:
						break;
					case 175:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -170:
						break;
					case 176:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -171:
						break;
					case 177:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -172:
						break;
					case 178:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -173:
						break;
					case 179:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -174:
						break;
					case 180:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -175:
						break;
					case 181:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -176:
						break;
					case 182:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -177:
						break;
					case 183:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -178:
						break;
					case 184:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -179:
						break;
					case 185:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -180:
						break;
					case 186:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -181:
						break;
					case 187:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -182:
						break;
					case 188:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -183:
						break;
					case 189:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -184:
						break;
					case 190:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -185:
						break;
					case 191:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -186:
						break;
					case 192:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -187:
						break;
					case 193:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -188:
						break;
					case 194:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -189:
						break;
					case 195:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -190:
						break;
					case 196:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -191:
						break;
					case 197:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -192:
						break;
					case 198:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -193:
						break;
					case 199:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -194:
						break;
					case 200:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -195:
						break;
					case 201:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -196:
						break;
					case 202:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -197:
						break;
					case 203:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -198:
						break;
					case 204:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -199:
						break;
					case 205:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -200:
						break;
					case 206:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -201:
						break;
					case 207:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -202:
						break;
					case 208:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -203:
						break;
					case 209:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -204:
						break;
					case 210:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -205:
						break;
					case 211:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -206:
						break;
					case 212:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -207:
						break;
					case 213:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -208:
						break;
					case 214:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -209:
						break;
					case 215:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -210:
						break;
					case 216:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -211:
						break;
					case 217:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -212:
						break;
					case 218:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -213:
						break;
					case 219:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -214:
						break;
					case 220:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -215:
						break;
					case 221:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -216:
						break;
					case 222:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -217:
						break;
					case 223:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -218:
						break;
					case 224:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -219:
						break;
					case 225:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -220:
						break;
					case 226:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -221:
						break;
					case 227:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -222:
						break;
					case 228:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -223:
						break;
					case 229:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -224:
						break;
					case 230:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -225:
						break;
					case 231:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -226:
						break;
					case 232:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -227:
						break;
					case 233:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -228:
						break;
					case 234:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -229:
						break;
					case 235:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -230:
						break;
					case 236:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -231:
						break;
					case 237:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -232:
						break;
					case 238:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -233:
						break;
					case 239:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -234:
						break;
					case 240:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -235:
						break;
					case 241:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -236:
						break;
					case 242:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -237:
						break;
					case 243:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -238:
						break;
					case 244:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -239:
						break;
					case 245:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -240:
						break;
					case 246:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -241:
						break;
					case 247:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -242:
						break;
					case 248:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -243:
						break;
					case 249:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -244:
						break;
					case 250:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -245:
						break;
					case 251:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -246:
						break;
					case 252:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -247:
						break;
					case 253:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -248:
						break;
					case 254:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -249:
						break;
					case 255:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -250:
						break;
					case 256:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -251:
						break;
					case 257:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -252:
						break;
					case 258:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -253:
						break;
					case 259:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -254:
						break;
					case 260:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -255:
						break;
					case 261:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -256:
						break;
					case 262:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -257:
						break;
					case 263:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -258:
						break;
					case 264:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -259:
						break;
					case 265:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -260:
						break;
					case 266:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -261:
						break;
					case 267:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -262:
						break;
					case 268:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -263:
						break;
					case 269:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -264:
						break;
					case 270:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -265:
						break;
					case 271:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -266:
						break;
					case 272:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -267:
						break;
					case 273:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -268:
						break;
					case 274:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -269:
						break;
					case 275:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -270:
						break;
					case 276:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -271:
						break;
					case 277:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -272:
						break;
					case 278:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -273:
						break;
					case 279:
						{ return new Symbol(sym.LabelIdent, yytext().intern()); }
					case -274:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
